# Use the official Node.js image from Docker Hub for building
FROM node:16 AS build

WORKDIR /deps

# Copy package.json and package-lock.json for installing dependencies
COPY ./node_src/package*.json ./

# Install the Node.js dependencies
RUN npm install

FROM ghcr.io/fivexl/secure-container-image-distroless_base_node:latest AS runtime

# Copy over the deps
COPY --from=build /deps /app
# Copy the rest of the project over
COPY ./node_src/app /app

CMD ["server.js"]