ARG DEBIAN_VERSION=11

FROM debian:${DEBIAN_VERSION} AS build

ARG POETRY_VERSION=1.6.1
ARG LIBPYTHON3_VERSION=3.9.2-3
ARG GCC_VERSION=4:10.2.1-1
ARG PYTHON3_VERSION=3.9.2-3
ARG PYTHON3_PIP_VERSION=20.3.4-4+deb11u1

RUN apt-get update && \
  apt-get install --no-install-suggests --no-install-recommends --yes python3=${PYTHON3_VERSION} python3-pip=${PYTHON3_PIP_VERSION} gcc=${GCC_VERSION} libpython3-dev=${LIBPYTHON3_VERSION} && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  pip install --no-cache-dir "poetry==${POETRY_VERSION}"

# Copy just the pyproject.toml and poetry.lock files to install dependencies
COPY ./py_src/pyproject.toml ./py_src/poetry.lock /

# Disable the creation of virtual environments and install app dependencies
RUN poetry config virtualenvs.create false && \
  poetry config virtualenvs.in-project false && \
  poetry install 

# Copy the rest of the project over and build the app
# hadolint ignore=DL3007
FROM ghcr.io/fivexl/secure-container-image-base-python3-distroless-debian-11:latest AS runtime

# Set the PYTHONPATH to the deps directory
ENV PYTHONPATH="/usr/bin/deps"

# Copy dependencies from the build stage
COPY --from=build /usr/lib/python3.9/site-packages/ /usr/bin/deps/

# Copy uvicorn executable from the build stage
COPY --from=build /usr/bin/uvicorn /usr/bin/uvicorn

WORKDIR /app
# Copy the rest of the project over
COPY ./py_src ./app

EXPOSE 80

ENTRYPOINT ["/usr/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

