
ARG ALPINE_VERSION=3.18
ARG BASE_IMAGE_VERSION=latest

# build stage
FROM golang:1.20.5-alpine${ALPINE_VERSION} AS builder
COPY ./gosrc/main.go /go/main.go
RUN go build -o app

# Actual runtime image
FROM ghcr.io/fivexl/secure-container-image-base:${BASE_IMAGE_VERSION}
COPY --from=builder /app /app/app
EXPOSE 8080
ENTRYPOINT ["/app/app"]
HEALTHCHECK --interval=1m --timeout=3s \
  CMD ["lprobe", "-mode=http", "-endpoint=/", "-port=8080"]
