# build stage
FROM golang:1.20.5-alpine3.18 AS builder
COPY ./gosrc/main.go .
RUN go build -o app

# Actual runtime image
FROM URL-to-DOckerfile.scratch-build
COPY --from=builder /app /app/app
EXPOSE 8080
ENTRYPOINT /app/app
HEALTHCHECK --interval=1m --timeout=3s \
  CMD lprobe -mode=http -endpoint=/ -port=8080