name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx (buildkit) runner
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.base

      - name: Build Docker image Base
        id: docker_build_base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.base
          pull: true
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-base:latest
            ghcr.io/fivexl/secure-container-image-base:${{ github.sha }}
          build-args: |
            ALPINE_VERSION: 3.18

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.goapp

      - name: Build Docker image goapp
        id: docker_build_goapp
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.goapp
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-goapp:latest
            ghcr.io/fivexl/secure-container-image-goapp:${{ github.sha }}
          build-args: |
            ALPINE_VERSION: 3.18
            BASE_IMAGE_VERSION: ${{ github.sha }}

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.python3-distroless-debian-11
      
      - name: Build base python3 distroless image
        id: docker_build_base_python3_distroless_image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.python3-distroless-debian-11
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-python3-distroless-debian-11:latest
            ghcr.io/fivexl/secure-container-image-python3-distroless-debian-11:${{ github.sha }}
          build-args: |
            BASE_IMAGE_VERSION: ${{ github.sha }}

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.nodejs20-distroless-debian-11

      - name: Build base nodejs20 distroless image
        id: docker_build_base_nodejs20_distroless_image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.nodejs20-distroless-debian-11
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-nodejs20-distroless-debian-11:latest
            ghcr.io/fivexl/secure-container-image-nodejs20-distroless-debian-11:${{ github.sha }}

      # Build poetry_example Python image
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.py-app-poetry

      - name: Build Docker image py-app-poetry
        id: docker_build_poetry_example
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.py-app-poetry
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-py-app-poetry:latest
            ghcr.io/fivexl/secure-container-image-py-app-poetry:${{ github.sha }}

      # Build poetry_without_venv_example Python image
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.py-app-poetry-no-venv

      - name: Build Docker image py-app-poetry-no-venv
        id: docker_build_poetry_without_venv_example
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.py-app-poetry-no-venv
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-py-app-poetry-no-venv:latest
            ghcr.io/fivexl/secure-container-image-py-app-poetry-no-venv:${{ github.sha }}

      # Build example node image
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.node-app
        
      - name: Build Docker image node-app
        id: docker_build_node_app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.node-app
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-node-app:latest
            ghcr.io/fivexl/secure-container-image-node-app:${{ github.sha }}

  # Run Snyk to check Docker image for vulnerabilities
  snyk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - secure-container-image-base
          - secure-container-image-base-distroless
          - secure-container-image-distroless_base_node
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/fivexl/${{ matrix.image }}:${{ github.sha }}
          args: --severity-threshold=high --sarif-file-output=${{ matrix.image }}_snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ matrix.image }}_snyk.sarif

            

            

      
