name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx (buildkit) runner
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.base

      - name: Build Docker image Base
        id: docker_build_base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.base
          pull: true
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-base:latest
            ghcr.io/fivexl/secure-container-image-base:${{ github.sha }}
          build-args: |
            ALPINE_VERSION: 3.18

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.base-python3-distroless-debian-11
      
      - name: Build base python3 distroless image
        id: docker_build_base_python3_distroless_image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.base-python3-distroless-debian-11
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-base-python3-distroless-debian-11:latest
            ghcr.io/fivexl/secure-container-image-base-python3-distroless-debian-11:${{ github.sha }}
          build-args: |
            BASE_IMAGE_VERSION: ${{ github.sha }}

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.base-nodejs20-distroless-debian-11

      - name: Build base nodejs20 distroless image
        id: docker_build_base_nodejs20_distroless_image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.base-nodejs20-distroless-debian-11
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-base-nodejs20-distroless-debian-11:latest
            ghcr.io/fivexl/secure-container-image-base-nodejs20-distroless-debian-11:${{ github.sha }}

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./examples/go_app_example/Dockerfile.goapp

      - name: Build Docker image goapp
        id: docker_build_goapp
        uses: docker/build-push-action@v3
        with:
          context: ./examples/go_app_example/
          file: ./examples/go_app_example/Dockerfile.goapp
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-example-goapp:latest
            ghcr.io/fivexl/secure-container-image-example-goapp:${{ github.sha }}
          build-args: |
            ALPINE_VERSION: 3.18
            BASE_IMAGE_VERSION: ${{ github.sha }}

      # Build py-app-poetry Python image
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./examples/python_examples/Dockerfile.py-app-poetry

      - name: Build Docker image py-app-poetry
        id: docker_build_poetry_example
        uses: docker/build-push-action@v3
        with:
          context: ./examples/python_examples/
          file: ./examples/python_examples/Dockerfile.py-app-poetry
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-example-py-app-poetry:latest
            ghcr.io/fivexl/secure-container-image-example-py-app-poetry:${{ github.sha }}

      # Build py-app-poetry-no-venv Python image
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./examples/python_examples/Dockerfile.py-app-poetry-no-venv

      - name: Build Docker image py-app-poetry-no-venv
        id: docker_build_poetry_without_venv_example
        uses: docker/build-push-action@v3
        with:
          context: ./examples/python_examples/
          file: ./examples/python_examples/Dockerfile.py-app-poetry-no-venv
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-example-py-app-poetry-no-venv:latest
            ghcr.io/fivexl/secure-container-image-example-py-app-poetry-no-venv:${{ github.sha }}

      # Build example node image
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./examples/node_examples/Dockerfile.node-app
        
      - name: Build Docker image node-app
        id: docker_build_node_app
        uses: docker/build-push-action@v3
        with:
          context: ./examples/node_examples/
          file: ./examples/node_examples/Dockerfile.node-app
          push: true
          tags: |
            ghcr.io/fivexl/secure-container-image-example-node-app:latest
            ghcr.io/fivexl/secure-container-image-example-node-app:${{ github.sha }}

# Run Snyk to check Docker image for vulnerabilities
  snyk:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        config:
          - {image: "secure-container-image-base", dockerfile: "Dockerfile.base"}
          - {image: "secure-container-image-python3-distroless-debian-11", dockerfile: "Dockerfile.python3-distroless-debian-11"}
          - {image: "secure-container-image-nodejs20-distroless-debian-11", dockerfile: "Dockerfile.nodejs20-distroless-debian-11"}
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/fivexl/${{ matrix.config.image }}:${{ github.sha }}
          args: --severity-threshold=high --file=${{ matrix.config.dockerfile }}

