name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx (buildkit) runner
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image Base
        id: docker_build_base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.base
          push: true
          load: true
          tags: |
            ghcr.io/fivexl/secure-container-image-base:latest
            ghcr.io/fivexl/secure-container-image-base:${{ github.sha }}
          build-args: |
            ALPINE_VERSION: 3.18

      - name: Check docker images
        run: docker images

      - name: Build Docker image goapp
        id: docker_build_goapp
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.goapp
          push: true
          load: true
          tags: |
            ghcr.io/fivexl/secure-container-image-goapp:latest
            ghcr.io/fivexl/secure-container-image-goapp:${{ github.sha }}
          build-args: |
            ALPINE_VERSION: 3.18
            BASE_IMAGE_VERSION: ${{ github.sha }}
            

      
